### ISSUE TITLE
i have an error in chat_room_screen.dart file

### ISSUE THREAD

**Issue by MominRaza** [KhalidWar/yaanyo#1]
on line no 41 Undefined name 'ScaffoldMessenger'.

https://github.com/KhalidWar/yaanyo/blob/main/lib/screens/chat/chat_room_screen.dart#L41

**Comment by KhalidWar** [comment]
That's the latest way of showing snackbars. Make sure you're running flutter 1.22+.
 
This is what I'm running: 
[✓] Flutter (Channel master, 1.24.0-8.0.pre.144, on Linux, locale en_US.UTF-8)
